<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Models\Cubs\Cubs;
use App\Models\UnidadEjecutora\UnidadEjecutora;

class CubSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        DB::table('cubs')->insert([
            [
                'IDUNSPSC' => 26111532,
                'descripcion_esp' => 'Soportes o conjuntos del eje',
                'descripcion_regional' => 'Soportes o conjuntos del eje',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26111601,
                'descripcion_esp' => 'Generadores diesel',
                'descripcion_regional' => 'Generadores diesel',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 25202402,
                'descripcion_esp' => 'Tanques para la caída de combustible de avión',
                'descripcion_regional' => 'Tanques para la caída de combustible de avión',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 25201706,
                'descripcion_esp' => 'Electrónica de interfaz del avión',
                'descripcion_regional' => 'Electrónica de interfaz del avión',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26111719,
                'descripcion_esp' => 'Probadores de baterías',
                'descripcion_regional' => 'Probadores de baterías',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26111723,
                'descripcion_esp' => 'Puertas, tapas o cajas de baterías',
                'descripcion_regional' => 'Puertas, tapas o cajas de baterías',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26111803,
                'descripcion_esp' => 'Correas redondas',
                'descripcion_regional' => 'Correas redondas',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26111807,
                'descripcion_esp' => 'Polea de distribución',
                'descripcion_regional' => 'Polea de distribución',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31101714,
                'descripcion_esp' => 'Piezas de estaño fundidas en molde fijo',
                'descripcion_regional' => 'Piezas de estaño fundidas en molde fijo',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31101801,
                'descripcion_esp' => 'Piezas de aleación no ferrosa fundidas por moldeo en cáscara',
                'descripcion_regional' => 'Piezas de aleación no ferrosa fundidas por moldeo en cáscara',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31101805,
                'descripcion_esp' => 'Piezas de hierro fundidas por moldeo en cáscara',
                'descripcion_regional' => 'Piezas de hierro fundidas por moldeo en cáscara',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31101808,
                'descripcion_esp' => 'Piezas de titanio fundidas por moldeo en cáscara',
                'descripcion_regional' => 'Piezas de titanio fundidas por moldeo en cáscara',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 60101205,
                'descripcion_esp' => 'Tarjetas perforadas de incentivo',
                'descripcion_regional' => 'Tarjetas perforadas de incentivo para la educacion',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26111518,
                'descripcion_esp' => 'Puntal tensor',
                'descripcion_regional' => 'Puntal tensor',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26142004,
                'descripcion_esp' => 'Irradiadores de neutrones',
                'descripcion_regional' => 'Irradiadores de neutrones',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26142007,
                'descripcion_esp' => 'Generadores de neutrones',
                'descripcion_regional' => 'Generadores de neutrones',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 26142106,
                'descripcion_esp' => 'Sistemas de varilla de mando para reactores nucleares',
                'descripcion_regional' => 'Sistemas de varilla de mando para reactores nucleares',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'IDUNSPSC' => 26121636,
                'descripcion_esp' => 'Cables de alimentación',
                'descripcion_regional' => 'Cordón de alimentación',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 60121208,
                'descripcion_esp' => 'Pintura de rotulador de cuerpo o cara',
                'descripcion_regional' => 'Pintura de rotulador de cuerpo o cara',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 60121212,
                'descripcion_esp' => 'Pintura acrílica de aerógrafo',
                'descripcion_regional' => 'Pintura acrílica de aerógrafo',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 80141617,
                'descripcion_esp' => 'Capacitación de iniciativas estratégicas en el concesionario',
                'descripcion_regional' => 'Capacitación de iniciativas estratégicas en el concesionario',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 73101602,
                'descripcion_esp' => 'Servicios de producción de ceniza de sosa o cloro o sosa cáustica',
                'descripcion_regional' => 'Servicios de producción de ceniza de sosa o cloro o sosa cáustica',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 73101606,
                'descripcion_esp' => 'Servicios de producción de etileno o derivados',
                'descripcion_regional' => 'Servicios de producción de etileno o derivados',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 72101901,
                'descripcion_esp' => 'Diseño o decoración de interiores',
                'descripcion_regional' => 'Diseño o decoración de interiores',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31101901,
                'descripcion_esp' => 'Piezas de aleación no ferrosa fundidas a la cera perdida',
                'descripcion_regional' => 'Piezas de aleación no ferrosa fundidas a la cera perdida',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 25111505,
                'descripcion_esp' => 'Buques cisterna',
                'descripcion_regional' => 'Buques cisterna',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 82121801,
                'descripcion_esp' => 'Publicación de libros de texto o investigación',
                'descripcion_regional' => 'Publicación de libros de texto o investigación',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 85122102,
                'descripcion_esp' => 'Servicios de terapia ocupacional',
                'descripcion_regional' => 'Servicios de terapia ocupacional',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 42222309,
                'descripcion_esp' => 'Sistemas de conservación de administración o transfusión sanguínea',
                'descripcion_regional' => 'Materiales para transfusión sanguínea',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 42231505,
                'descripcion_esp' => 'Adaptores o conectadores o extensiones de los equipos de alimentación enteral',
                'descripcion_regional' => 'Adaptores o conectadores o extensiones de los equipos de alimentación enteral',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 42231510,
                'descripcion_esp' => 'Sets de tubos de bombas de infusión de alimentación enteral',
                'descripcion_regional' => 'Sets de tubos de bombas de infusión de alimentación enteral',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31131908,
                'descripcion_esp' => 'Forjaduras anulares laminadas de magnesio',
                'descripcion_regional' => 'Forjaduras anulares laminadas de magnesio',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31131911,
                'descripcion_esp' => 'Forjaduras anulares laminadas de estaño',
                'descripcion_regional' => 'Forjaduras anulares laminadas de estaño',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31141802,
                'descripcion_esp' => 'Moldeados de inyección de reacción de goma',
                'descripcion_regional' => 'Moldeados de inyección de reacción de goma',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 31191509,
                'descripcion_esp' => 'Pulidores abrasivos',
                'descripcion_regional' => 'Pulidores abrasivos',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 51172004,
                'descripcion_esp' => 'Sulfóxido de dimetilo',
                'descripcion_regional' => 'Sulfóxido de dimetilo',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 51201704,
                'descripcion_esp' => 'Bronquitis infecciosa aviar',
                'descripcion_regional' => 'Bronquitis infecciosa aviar',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 51201803,
                'descripcion_esp' => 'Pegfilgrastim',
                'descripcion_regional' => 'Pegfilgrastim',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 24101703,
                'descripcion_esp' => 'Acumuladoras de rocas',
                'descripcion_regional' => 'Acumuladoras de rocas',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 24101707,
                'descripcion_esp' => 'Raíles de transportador',
                'descripcion_regional' => 'Raíles de transportador',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 24101712,
                'descripcion_esp' => 'Cintas transportadoras de correas',
                'descripcion_regional' => 'Banda o cintas transportadoras de correas',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 24101716,
                'descripcion_esp' => 'Poleas de transportador',
                'descripcion_regional' => 'Poleas de transportador',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 10161602,
                'descripcion_esp' => 'Poinsetias o flores de Pascua',
                'descripcion_regional' => 'Poinsetias o flores de Pascua',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 49131605,
                'descripcion_esp' => 'Escopetas deportivas',
                'descripcion_regional' => 'Escopetas deportivas',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 49141502,
                'descripcion_esp' => 'Tanques de aire comprimido para buceo',
                'descripcion_regional' => 'Tanques de aire comprimido para buceo',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 23151809,
                'descripcion_esp' => 'Máquinas farmacéuticas de tamiz o criba',
                'descripcion_regional' => 'Máquinas farmacéuticas de tamiz o criba',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 23151812,
                'descripcion_esp' => 'Contadores de tabletas',
                'descripcion_regional' => 'Contadores de tabletas',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDUNSPSC' => 23151817,
                'descripcion_esp' => 'Medios de cromatografía',
                'descripcion_regional' => 'Medios de cromatografía',
                'idUE' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            

        ]);
    }
}