<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ObjetoGastoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('objetogastos')->insert([
            [
                'nombre' => "Sueldos Básicos",
                'descripcion' => "Asignaciones por remuneraciones al personal de carácter permanente (excepto sueldos para personal docente que se clasifica en la partida (112. sueldos básicos educación), que ha sido nombrado de acuerdo a las leyes y normativas vigente, por la contraprestación del trabajo realizado. No incluye los adicionales por características individuales del empleado o circunstancias del cargo o función(a excepción de la antiguedad) nombrado de acuerdo a las leyes y normativas vigentes, por la contraprestación del trabajo realizado. No incluye los adicionales por características individuales del empleado o circunstanciales del cargo o función (a excepción de la antigüedad).",
                'identificador' => 11100,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Sueldos Básicos Educación",
                'descripcion' => "Asignaciones por remuneraciones al personal docente de carácter permanente según horas cátedra y docente con funciones en cargos administrativos. No incluye los adicionales por características individuales del empleado o circunstanciales del cargo o función (a excepción de la antigüedad).",
                'identificador' => 11200,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Sueldos Básicos Docentes",
                'descripcion' => "No Definido",
                'identificador' => 11210,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Sueldos Básicos Docentes Administrativos",
                'descripcion' => "No Definido",
                'identificador' => 11220,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Retribuciones a Personal Directo y de Control",
                'descripcion' => "Asignaciones en concepto de retribuciones a miembros de los Directorios y Comisiones de Fiscalización de Empresas Públicas.",
                'identificador' => 11300,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Adicionales",
                'descripcion' => "Asignaciones remunerativas que de acuerdo a la legislación vigente, corresponden a las características individuales de los empleados y funcionarios o circunstanciales del cargo o función que desempeña: título, riesgo, jefatura, cargo administrativo, zonaje, turnicidad, turno mixto, nocturnidad, etc.",
                'identificador' => 11400,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Decimotercer mes",
                'descripcion' => "No Definido",
                'identificador' => 11510,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1
            ],
            [
                'nombre' => "Decimocuarto mes",
                'descripcion' => "No Definido",
                'identificador' => 11520,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Decimotercer mes Docentes",
                'descripcion' => "No Definido",
                'identificador' => 11530,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Decimotercer mes Docentes Administrativos",
                'descripcion' => "No Definido",
                'identificador' => 11540,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Decimocuarto mes Docentes",
                'descripcion' => "No Definido",
                'identificador' => 11550,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 1,
            ],
            [
                'nombre' => "Mantenimiento y Reparación de Equipos Sanitarios y de Laboratorio",
                'descripcion' => "No Definido",
                'identificador' => 23330,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Mantenimiento y Reparación de Equipo Educacional",
                'descripcion' => "No Definido",
                'identificador' => 23340,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Mantenimiento y Reparación de Equipo para Computación",
                'descripcion' => "No Definido",
                'identificador' => 23350,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Mantenimiento y Reparación de Equipo de Oficina y Muebles",
                'descripcion' => "No Definido",
                'identificador' => 23360,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Mantenimiento y Reparación de Equipos de Comunicación",
                'descripcion' => "No Definido",
                'identificador' => 23370,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Mantenimiento y Reparación de Otros Equipos",
                'descripcion' => "No Definido",
                'identificador' => 23390,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Mantenimiento y Reparación de Obras Civiles e Instalaciones Varias",
                'descripcion' => "Mantenimiento y conservación de canales de riego, defensas contra inundaciones y otras obras hidráulicas; sistemas de agua potable, alcantarillado y sistemas cloacales; plazas, parques y recreos; líneas de distribución de energía eléctrica; líneas telefónicas y telegráficas; carreteras, caminos, puentes, vías férreas, aeródromos, fluviales, dragado de canales de navegación y otras construcciones civiles.",
                'identificador' => 23400,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Limpieza, Aseo y Fumigación",
                'descripcion' => "Servicio de extracción de basura, fumigación, desinfección y limpieza general de edificios y oficinas públicas.",
                'identificador' => 23500,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Mantenimiento de Sistemas Informáticos",
                'descripcion' => "Servicio de mantenimiento y actualización de software correspondiente a sistemas informáticos.",
                'identificador' => 23600,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "SERVICIOS PROFESIONALES",
                'descripcion' => "Asignaciones por servicios profesionales prestados por empresas, profesionales y especialistas sin relación de dependencia con la institución. Incluye los honorarios legales o reconocidos de peritos, especialistas, técnicos, artistas y deportistas sin relación de dependencia y servicios de consultoría y asesoría relacionados con estudios, investigación, análisis, auditorias, sistemas computarizados, etc. prestados por empresas, fundaciones, ONG, etc. Incluye contratos de servicios profesionales prestados a título personal que no obligan a pagos con periodicidad mensual. Se imputan en esta partida los servicios de terceros contratados para la realización de estudios, investigaciones y otras actividades técnico-profesionales para facilitar el funcionamiento u operación de la institución o que forman parte de un proyecto de inversión. Los servicios profesionales incluyen servicios jurídicos, servicios de contabilidad y auditoría, servicios de capacitación, servicios de informática, estudios, asesorías e investigaciones tales como: interpretaciones de asuntos técnicos, económicos y sociales; investigaciones sociales, estadísticas, científicas, técnicas, económicas, relacionadas con ingeniería o arquitectura y otros servicios profesionales de igual naturaleza.",
                'identificador' => 24000,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 2,
            ],
            [
                'nombre' => "Productos Farmacéuticos y Medicinales Varios",
                'descripcion' => "No Definido",
                'identificador' => 35210,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Vacunas",
                'descripcion' => "No Definido",
                'identificador' => 35220,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Antirretrovirales",
                'descripcion' => "No Definido",
                'identificador' => 35230,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Anticonceptivos",
                'descripcion' => "No Definido",
                'identificador' => 35240,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Abonos y Fertilizantes",
                'descripcion' => "Abonos nitrogenados, fosfatados y potásicos puros, mixtos, compuestos y complejos. Entre otros, incluye urea, ácido nítrico, amoníaco, cloruro de amonio comercial y nitrato de potasio.",
                'identificador' => 35300,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Insecticidas, Fungicidas y Otros",
                'descripcion' => "Insecticidas, raticidas, funguicidas, plaguicidas, herbicidas, productos anti germinantes, desinfectantes y otros productos químicos de similares características y usos.",
                'identificador' => 35400,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Tintas, Pinturas y Colorantes",
                'descripcion' => "Tintas para escribir, dibujar e imprenta. Incluye pinturas, barnices, esmaltes y lacas, pigmentos y colores preparados, masillas y preparados similares no refractarios, para relleno y enlucido, disolventes, diluyentes y removedores de pintura. No incluye cartuchos de tinta de fotocopiadoras e impresoras (se incluye en la partida 39600 – Repuestos y accesorios).",
                'identificador' => 35500,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "COMBUSTIBLES Y LUBRICANTES",
                'descripcion' => "Productos derivados del petróleo, como gasolina, aceites ligeros usados como carburantes, keroseno, diésel y grasas lubricantes, gas natural y artificial; líquido de frenos y aceite para equipos de oficina.",
                'identificador' => 35600,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Gasolina",
                'descripcion' => "No Definido",
                'identificador' => 35610,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Diesel",
                'descripcion' => "No Definido",
                'identificador' => 35620,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Kerosén",
                'descripcion' => "No Definido",
                'identificador' => 35630,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Gas LPG",
                'descripcion' => "No Definido",
                'identificador' => 35640,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Aceites y Grasas Lubricantes",
                'descripcion' => "No Definido",
                'identificador' => 35650,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Bunker",
                'descripcion' => "No Definido",
                'identificador' => 35660,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Específicos Veterinarios y Productos Varios para Animales",
                'descripcion' => "Medicamentos y productos farmacéuticos veterinarios y demás artículos para uso veterinario.",
                'identificador' => 35700,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Productos de Material Plástico",
                'descripcion' => "Artículos diversos de material plástico, tales como láminas, lienzos, bolsas, tubos, recipientes, envases y accesorios de PVC, polipropileno, etc. No incluye los artículos de cocina y comedor clasificados en \"3.9.4.00 - Utensilios de Cocina y Comedor\".",
                'identificador' => 35800,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "OTROS PRODUCTOS QUIMICOS",
                'descripcion' => "Otros productos químicos no calificados precedentemente como explosivos, productos de pirotecnia, pólvora propulsora, mechas detonadoras y de seguridad, fuegos artificiales, bengalas, etc. Placas fotográficas, películas, papel sensibilizado y preparados químicos de uso fotográfico. Preparados aromáticos de uso personal como perfumes, agua de colonia y de tocados; preparados de aseo personal como jabones de tocador, gel de baño, champo, crema acondicionadora de cabello; preparados para la higiene buco-dental y preparados de belleza y maquillaje. Incluye.",
                'identificador' => 35900,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Productos Explosivos y de Pirotecnia",
                'descripcion' => "No Definido",
                'identificador' => 35910,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Productos Fotoquímicos",
                'descripcion' => "No Definido",
                'identificador' => 35920,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Productos Químicos de Uso Personal",
                'descripcion' => "No Definido",
                'identificador' => 35930,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 3,
            ],
            [
                'nombre' => "Intereses por Préstamos de Gobiernos Locales",
                'descripcion' => "No Definido",
                'identificador' => 72260,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses por Préstamos de Empresas Públicas no Financieras",
                'descripcion' => "No Definido",
                'identificador' => 72270,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses por Préstamos de Instituciones Públicas Financieras",
                'descripcion' => "No Definido",
                'identificador' => 72280,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses Otras Deudas a Largo Plazo",
                'descripcion' => "No Definido",
                'identificador' => 72290,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Comisiones y Otros Gastos de la Deuda Pública Interna a Largo Plazo",
                'descripcion' => "Asignaciones derivadas de la deuda pública interna que se originan en comisiones, multas, estampillas y otros gastos no incluidos en las cuentas anteriores.",
                'identificador' => 72300,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses por Mora y Multas de la Deuda Pública Interna a Largo Plazo",
                'descripcion' => "Asignaciones destinadas para gastos por intereses por mora y multas de la deuda pública interna a largo plazo",
                'identificador' => 72400,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "SERVICIO DE LA DEUDA PUBLICA EXTERNA A CORTO PLAZO",
                'descripcion' => "Asignaciones para el pago de intereses, amortizaciones y otros gastos de la deuda externa a corto plazo de instituciones del Sector Público, representada por títulos, bonos, convenios de préstamos, etc., documentados de acuerdo a normas vigentes",
                'identificador' => 73000,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Amortización de la Deuda Pública Externa a Corto Plazo",
                'descripcion' => "Asignaciones destinadas para amortización de deuda pública externa de corto plazo asumida mediante colocación de títulos y valores y préstamos.",
                'identificador' => 73100,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses de la Deuda Pública Externa a Corto Plazo",
                'descripcion' => "Asignaciones destinadas para gastos por intereses de la deuda pública externa a corto plazo.",
                'identificador' => 73200,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Comisiones y Otros Gastos de la Deuda Externa a Corto Plazo",
                'descripcion' => "Asignaciones de gastos derivados de la deuda pública externa que se originan en comisiones, multas, diferencias por variaciones de tipo de cambio en el servicio del endeudamiento.",
                'identificador' => 73300,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses por Mora y Multas de la Deuda Pública Externa a Corto Plazo",
                'descripcion' => "Asignaciones destinadas para gastos por intereses por mora y multas de la deuda pública externa a corto plazo.",
                'identificador' => 73400,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "SERVICIO DE LA DEUDA PUBLICA EXTERNA A LARGO PLAZO",
                'descripcion' => "Asignaciones para el pago de intereses, amortizaciones y otros gastos de la deuda externa a largo plazo de instituciones del Sector Público, representada por títulos, bonos, convenios de préstamos, etc., documentados de acuerdo a normas vigentes.",
                'identificador' => 74000,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Amortización de la Deuda Pública Externa a Largo Plazo",
                'descripcion' => "Asignaciones destinadas para amortización de deuda pública externa de largo plazo asumida mediante colocación de títulos y valores y préstamos.",
                'identificador' => 74100,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses de la Deuda Pública Externa a Largo Plazo",
                'descripcion' => "Asignaciones destinadas para gastos por intereses de la deuda pública externa a largo plazo.",
                'identificador' => 74200,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Comisiones y Otros Gastos de la Deuda Pública Externa a Largo Plazo",
                'descripcion' => "Asignaciones de gastos derivados de la deuda pública externa que se originan en comisiones, multas, diferencias por variaciones de tipo de cambio en el servicio del endeudamiento",
                'identificador' => 74300,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses por Mora y Multas de la Deuda Pública Externa a Largo Plazo",
                'descripcion' => "Asignaciones destinadas para gastos por intereses por mora y multas de la deuda pública externa a largo plazo.",
                'identificador' => 74400,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Amortización por Alivio Deuda Pública Externa",
                'descripcion' => "Asignaciones de gastos derivados del alivio de la deuda pública externa que corresponde a comisiones, multas, diferencias por variaciones de tipo de cambio en el servicio del endeudamiento.",
                'identificador' => 74500,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses por Alivio Deuda Pública Externa",
                'descripcion' => "Asignaciones destinadas para gastos por intereses por alivio de la deuda pública externa.",
                'identificador' => 74600,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Comisiones por Alivio Deuda Pública Externa",
                'descripcion' => "Asignaciones derivadas del alivio de la deuda pública externa que corresponde a comisiones, multas, diferencias por variaciones de tipo de cambio en el servicio del endeudamiento.",
                'identificador' => 74700,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "COMISIONES Y OTROS GASTOS",
                'descripcion' => "Asignaciones derivadas por comisiones y otros gastos.",
                'identificador' => 74800,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Comisiones y Otros Gastos por Reembolsos de PPF",
                'descripcion' => "No Definido",
                'identificador' => 74810,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Comisión de Inspección y Vigilancia",
                'descripcion' => "No Definido",
                'identificador' => 74820,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Intereses",
                'descripcion' => "No Definido",
                'identificador' => 74830,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "OTRAS OBLIGACIONES A CARGO DEL TESORO",
                'descripcion' => "No Definido",
                'identificador' => 75000,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "GASTOS DEVENGADOS Y NO REGISTRADOS",
                'descripcion' => "No Definido",
                'identificador' => 76000,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "SENTENCIAS JUDICIALES",
                'descripcion' => "No Definido",
                'identificador' => 77000,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Sentencias Judiciales por Servicios Personales",
                'descripcion' => "No Definido",
                'identificador' => 77100,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Sentencias Judiciales por Servicios no Personales",
                'descripcion' => "No Definido",
                'identificador' => 77200,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Sentencias Judiciales por Materiales y Suministros",
                'descripcion' => "No Definido",
                'identificador' => 77300,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ],
            [
                'nombre' => "Sentencias Judiciales por Bienes Capitalizables",
                'descripcion' => "No Definido",
                'identificador' => 77400,
                'created_at' => '2023-07-03 19:05:49',
                'updated_at' => '2023-07-03 19:05:49',
                'idgrupo' => 7,
            ]
        ]);
        
    }
}
